version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: resources/Dockerfile
    environment:
      LOGGING: "false"
      DATABASE_DB: webtech
      DATABASE_USER: webtech
      DATABASE_PASS: webtech
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_SYNCHRONIZE: "true"
      ACCESS_TOKEN_EXPIRATION: 5m
      REFRESH_TOKEN_EXPIRATION: 1w
      RFRESH_TOKEN_COKKIE_NAME: jit
      ACCESS_TOKEN_HEADER_NAME: Token
      FRONTEND_DOMAINS: http://localhost:4200,http://localhost:8080
    ports:
      - 5000:5000
  postgres:
    image: postgres:11.5-alpine
    container_name: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: webtech
      POSTGRES_USER: webtech
      POSTGRES_PASS: webtech
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
volumes:
  postgres:
