version: "3"
services:
  backend:
    image: node:14
    container_name: backend
    volumes:
      - ./:/home/node/app
    command: tail -f /dev/null
    ports:
      - 5000:5000
    environment:
      LOGGING: "false"
      DATABASE_DB: webtech
      DATABASE_USER: webtech
      DATABASE_PASS: webtech
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_SYNCHRONIZE: "true"
      ACCESS_TOKEN_EXPIRATION: 5m
      REFRESH_TOKEN_EXPIRATION: 1w
      REFRESH_TOKEN_COOKIE_NAME: jit
      ACCESS_TOKEN_HEADER_NAME: Token
      JWT_SECRET: secret
      BASE_URL: http://localhost:4200
      FRONTEND_DOMAINS: http://localhost:4200,http://localhost:8080
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:11.5-alpine
    container_name: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: webtech
      POSTGRES_USER: webtech
      POSTGRES_PASS: webtech
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webtech"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: webtech@webtech.com
      PGADMIN_DEFAULT_PASSWORD: webtech
    ports:
      - 5050:80
volumes:
  postgres:
